services:
  smartgarden.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "8080"
      - "8081"
    volumes:
      - ${HOME}/.aspnet/https:/home/app/.aspnet/https/
      - ${HOME}/.microsoft/usersecrets:/home/app/.microsoft/usersecrets:ro
