services:
  smartgarden.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - "8080"
      - "8081"
    volumes:
      - ~/.aspnet/https:/https:ro
      - ${HOME}/.microsoft/usersecrets:/home/app/.microsoft/usersecrets:ro